### ISSUE TITLE
デザイン2パターンの方針決め #3

### ISSUE THREAD

**Issue by kynysk** [kynysk-org/sp-web#1]
TOPページに置こうと思っている各メニューとWORKS画像の構成案を2パターン作って比較したいと思います。

## TODO
- [ ] #2
- [ ] #3

**Comment by kynysk-test** [comment]
WORKS画像の閲覧方法は縦にスクロールするタイプと、1枚を横にスライドショー風に大きく見せる2つのタイプがあると良いと思います！

**Comment by kynysk-test** [comment]
それなら各メニューは縦スクロールなら上部に小さく、横スライドショーなら下部に大きく並べてみてはどうでしょう？？

**Comment by kynysk** [comment]
解決したのでクローズします。
